# copying projectile 
site_name: "ğ„ğŒğ€ğ‚ğ’ Disaster" 
repo_url: https://github.com/nverno/nvp
site_favicon: favicon.ico
docs_dir: doc
pages:
- Home: index.md
- Todo: todo.md
- Notes: notes.md
- Projects: projects.md
- Configuration: configuration.md
extra_css:
  - css/styles.css
markdown_extensions:
  - admonition
theme: readthedocs
